import { Classroom, AlarmItem, PatrolFeed, EnergyHourlyPoint, EnergyRankItem } from './types';

// Hotlinked media assets from the HTML template
export const MEDIA_ASSETS = {
  logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAcOV8UpuIbsgE61F_2sWr1Z7WMsBew3aNoF0GYEkBkh1WrQJJ95mhVJGFG6lQAiW66gsUefbt74RupwKYT1VzTS06Dq8aLAj6zApfGNqHYNvQ3OVcV3YWFhLrov4FdAgSc6gn2o4G55ayBalf40G6KKpK8VHlSyGrVlW1-VDpWSB2nB-fQAGgetm9iub4KWqmohFV4D2LEr51PYMp5UgkucrdR1fQJjs-Nl-eTo6s74_DXMlk-NIKx',
  teacherCam: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDrDEIuL7ZeTH6inmWj4xTSDB5_scQRs3BWkHY0y_4oSQjBTGCMhsXAWE0-hlas_T93jTGGvRjsqnU53piNEpG59j4O1Oq8CG8VGYMo5z89XYSiaTJyerxu99yZHJRTJsP-T4sXLSg7Xgm2JDpBLKTeB7H7dzn73qM5eUoyNOguqrG7DWpxEozxXQqTJYfUf1WrSN-OfRenVPiv5KgQAYRWIKyO1j9BYVduChYweOMJwZbNAf2rQ9ZRvA0sP5OlkHNDfw',
  studentCam: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAZ1RD34iQ-ubXErxH8QxLMjIfTu9C6K1XLvxJIdv-R-ixC1WAyIDh3IKzO-Wlx0KMg2AQIT_HsPqlQtLml58a6-3GjOeJR66nJEiNEzBXY24Cq0KzhsMcnUslSN6d8gDtIq452waqwc22J1xsQrHu2usNqEXyCJ22bejcL6-tmOHnTr7uCqk25Uq0VemTUef9FTcN0xFJyF1wE-dnYJkvQgK-PO5VT0lcW0cjFcXvJxZHxgpKWae0gggxuCJSgO3SR3A',
  cam3: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAV3KVhm1YtuKAmF06jNWBhfZoUEwm1NCLhNp17APA2Vxksn-iXBpudnu0_otBj8ILpik_NutUTPORiGuE8VeLsFwMXFlgm4ICoF0_lvEZpa-MNBeQrvcpOpZxven2rqttEZyhbqYHVULcWd9P3vZD0YmC6LlSAbdGWJJ0gfbpH3M5xU2oGVoYDWtDWpOoRie4a3F-hanl2Oz_1u6jddRtkEOt68CahDXfKX6bCgxAzi7oK53tbxIYL_8j2FeKTdmG4QQ',
  cam4: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAbbFvzWMoZfZadVLjasr2rNxIKAlSLUnAMzlOZw0HckdhY8EZo9oSifM0Cf5V_WqCr0XPNjP7apM0lP6w4eClktP78Xzj8cbd0WrYhl0BNxxdI7dnxJwYv0LN0yvYhy3cahXc6v2ZtD5Ku4q70RSZ-H9oYkVA2W2mDTAYDfkDigpyUtvlBygdc-wzLu-SRqXkcwCuE0ni7x2r7Ah19lVjv-JnKOuTG13wesTOI2oI46zDG9KMNc9_jk_Fv3RtVa6Uxzw',
  courseware: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCy6eYSMwiaNTVtaKToEBxB6h3H-7UEebVA31msnpmbyTcwBhN9BHbxkKgajinh93Z3G66e9AcV_UJMFU2nG-sQqg_XcnZh7jecm2dd-TJUUUB4GYtpWbZmGcA5FI3R2EL-ylHghWihs_THgg_5XwfsviKXahUD7VgkF28CzWxz1IdgdFNWqRGf7RPM942CmK-vI3vOOXdRQJisn2dHJGexpz4m5X1Cfcq_WvH2gBXFk3MrtlFswMNsKnyj3KCjbEuCjw',
};

export const INITIAL_CLASSROOMS: Classroom[] = [
  // 教学楼 1 (Group 1 - Left Block)
  {
    id: 'c-01',
    name: '初一(1)班',
    building: '教学楼1',
    buildingCode: 'A栋',
    roomCode: 'A-101 · 1F',
    floor: 1,
    grade: '初一',
    classNumber: '(1)班',
    status: 'good',
    statusText: '节能低耗 · 运行正常',
    powerWatts: 620,
    todayKwh: 4.8,
    weekKwh: 32.5,
    temperature: 23.8,
    humidity: 46,
    co2Ppm: 520,
    pm25: 14,
    headTeacher: '王晓芳',
    currentSubject: '语文',
    currentTeacher: '王晓芳 (高级教师)',
    courseTime: '08:30 - 11:45',
    studentCount: 45,
    presentCount: 45,
    isoPosition: { x: 50, y: 50, buildingGroup: 'b1' },
    cameras: {
      teacher: MEDIA_ASSETS.teacherCam,
      students: MEDIA_ASSETS.studentCam,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '86寸4K智慧白板 · 运行中' },
      lighting: { status: 'normal', text: '护眼智能照明群', mode: '自然光自适应 (50%)' },
      ac: { status: 'normal', text: '变频新风空调', temp: 24, mode: '变频ECO模式' },
      freshAir: { status: 'normal', text: '双向流新风系统', speed: '中速风' },
      projector: { status: 'normal', text: '激光高清投影' },
    },
    inspectionRecords: [
      {
        id: 'rec-1',
        level: 'normal',
        levelText: '正常',
        inspector: '督导组 张主任',
        time: '2026-09-02 09:15',
        statusText: '正常',
        content: '教学秩序井然，全班学生出勤率100%，板书与多媒体交互良好。',
        responsiblePerson: '王晓芳',
        deadline: '无须整改',
      },
    ],
    repairOrders: [],
  },
  {
    id: 'c-02',
    name: '初二(1)班',
    building: '教学楼1',
    buildingCode: 'A栋',
    roomCode: 'A-201 · 2F',
    floor: 2,
    grade: '初二',
    classNumber: '(1)班',
    status: 'normal',
    statusText: '能耗正常',
    powerWatts: 980,
    todayKwh: 6.2,
    weekKwh: 41.0,
    temperature: 24.2,
    humidity: 49,
    co2Ppm: 580,
    pm25: 16,
    headTeacher: '张建军',
    currentSubject: '英语',
    currentTeacher: 'Lucy Smith (外教)',
    courseTime: '09:15 - 10:00',
    studentCount: 42,
    presentCount: 42,
    isoPosition: { x: 120, y: 50, buildingGroup: 'b1' },
    cameras: {
      teacher: MEDIA_ASSETS.cam3,
      students: MEDIA_ASSETS.studentCam,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '智慧黑板正常' },
      lighting: { status: 'normal', text: '全光谱护眼灯', mode: '标准授课 (70%)' },
      ac: { status: 'normal', text: '空调制冷', temp: 23, mode: '标准模式' },
      freshAir: { status: 'normal', text: '新风系统', speed: '自动' },
      projector: { status: 'normal', text: '激光投影待机' },
    },
    inspectionRecords: [],
    repairOrders: [],
  },
  {
    id: 'c-03',
    name: '初三(1)班',
    building: '教学楼1',
    buildingCode: 'A栋',
    roomCode: 'A-301 · 3F',
    floor: 3,
    grade: '初三',
    classNumber: '(1)班',
    status: 'normal',
    statusText: '能耗正常',
    powerWatts: 1020,
    todayKwh: 6.5,
    weekKwh: 43.8,
    temperature: 24.0,
    humidity: 47,
    co2Ppm: 610,
    pm25: 15,
    headTeacher: '陈卫国',
    currentSubject: '物理',
    currentTeacher: '陈卫国 (高级教师)',
    courseTime: '10:10 - 10:55',
    studentCount: 46,
    presentCount: 46,
    isoPosition: { x: 190, y: 50, buildingGroup: 'b1' },
    cameras: {
      teacher: MEDIA_ASSETS.teacherCam,
      students: MEDIA_ASSETS.cam4,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '物理实验多媒体交互' },
      lighting: { status: 'normal', text: '智能照明', mode: '实验模式' },
      ac: { status: 'normal', text: '空调系统', temp: 24, mode: '制冷' },
      freshAir: { status: 'normal', text: '新风强风', speed: '高速' },
      projector: { status: 'normal', text: '投影仪开启' },
    },
    inspectionRecords: [],
    repairOrders: [],
  },
  {
    id: 'c-04',
    name: '初一(2)班',
    building: '教学楼1',
    buildingCode: 'A栋',
    roomCode: 'A-102 · 1F',
    floor: 1,
    grade: '初一',
    classNumber: '(2)班',
    status: 'normal',
    statusText: '运行正常',
    powerWatts: 920,
    todayKwh: 5.8,
    weekKwh: 38.6,
    temperature: 24.1,
    humidity: 45,
    co2Ppm: 540,
    pm25: 14,
    headTeacher: '周慧敏',
    currentSubject: '历史',
    currentTeacher: '周慧敏',
    courseTime: '10:10 - 10:55',
    studentCount: 44,
    presentCount: 43,
    isoPosition: { x: 50, y: 120, buildingGroup: 'b1' },
    cameras: {
      teacher: MEDIA_ASSETS.cam4,
      students: MEDIA_ASSETS.studentCam,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '智慧黑板运行中' },
      lighting: { status: 'normal', text: '照明系统', mode: '标准模式' },
      ac: { status: 'normal', text: '空调制冷', temp: 24, mode: '智能控温' },
      freshAir: { status: 'normal', text: '新风系统', speed: '标准' },
      projector: { status: 'normal', text: '投影仪休眠' },
    },
    inspectionRecords: [],
    repairOrders: [],
  },
  {
    id: 'c-05',
    name: '初二(2)班',
    building: '教学楼1',
    buildingCode: 'A栋',
    roomCode: 'A-202 · 2F',
    floor: 2,
    grade: '初二',
    classNumber: '(2)班',
    status: 'warning',
    statusText: '功耗偏高预警 · 非教学段持续运行',
    powerWatts: 1580,
    todayKwh: 9.8,
    weekKwh: 68.4,
    temperature: 21.5,
    humidity: 55,
    co2Ppm: 720,
    pm25: 22,
    headTeacher: '李慧敏',
    currentSubject: '数学',
    currentTeacher: '陈晓明 (骨干教师)',
    courseTime: '11:05 - 11:50',
    studentCount: 44,
    presentCount: 44,
    isoPosition: { x: 120, y: 120, buildingGroup: 'b1' },
    cameras: {
      teacher: MEDIA_ASSETS.teacherCam,
      students: MEDIA_ASSETS.studentCam,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '智慧触控白板运行中' },
      lighting: { status: 'normal', text: '照明系统全开', mode: '100% 满功率' },
      ac: { status: 'warning', text: '变频空调超低温', temp: 20, mode: '强力制冷 (高能耗)' },
      freshAir: { status: 'normal', text: '新风系统', speed: '最大档' },
      projector: { status: 'warning', text: '投影仪长时间开启' },
    },
    inspectionRecords: [
      {
        id: 'rec-2',
        level: 'warning',
        levelText: '一般问题',
        inspector: '教务处刘主任',
        time: '2026-09-01 09:22',
        statusText: '整改中',
        content: '后排靠窗第4组有3名学生低头做非本学科作业并有小声耳语，授课教师正在板书未能及时提醒。',
        responsiblePerson: '李慧敏 (班主任)',
        deadline: '2026-09-02 12:00',
      },
    ],
    repairOrders: [
      {
        id: 'rep-3',
        ticketNo: '#rep-3',
        device: '智慧黑板触控模组',
        status: 'completed',
        statusText: '维修已办结',
        description: '黑板右侧触摸有漂移，需重新校准红外触控驱动',
        reportTime: '2026-08-31 17:10',
        engineer: '张师傅 (厂家驻校工程师)',
        urgency: 'medium',
      },
    ],
  },
  {
    id: 'c-06',
    name: '初三(2)班',
    building: '教学楼1',
    buildingCode: 'A栋',
    roomCode: 'A-302 · 3F',
    floor: 3,
    grade: '初三',
    classNumber: '(2)班',
    status: 'critical',
    statusText: '高能耗告警 · 负荷超标',
    powerWatts: 2150,
    todayKwh: 14.2,
    weekKwh: 96.5,
    temperature: 21.0,
    humidity: 58,
    co2Ppm: 890,
    pm25: 28,
    headTeacher: '孙海涛',
    currentSubject: '化学',
    currentTeacher: '孙海涛',
    courseTime: '11:05 - 11:50',
    studentCount: 46,
    presentCount: 45,
    isoPosition: { x: 190, y: 120, buildingGroup: 'b1' },
    cameras: {
      teacher: MEDIA_ASSETS.cam3,
      students: MEDIA_ASSETS.studentCam,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '智慧黑板' },
      lighting: { status: 'warning', text: '灯光全开未关' },
      ac: { status: 'warning', text: '双空调全力运转', temp: 19, mode: '极限制冷' },
      freshAir: { status: 'warning', text: '排风扇过载' },
      projector: { status: 'normal', text: '投影开启' },
    },
    inspectionRecords: [
      {
        id: 'rec-3',
        level: 'critical',
        levelText: '严重问题',
        inspector: '后勤能耗督查',
        time: '2026-09-02 10:30',
        statusText: '处理中',
        content: '空调设定19度且门窗未完全关闭，瞬时功率超过2.1kW阈值。',
        responsiblePerson: '孙海涛',
        deadline: '今日立即调整',
      },
    ],
    repairOrders: [
      {
        id: 'rep-6',
        ticketNo: '#rep-6',
        device: '空调智能网关',
        status: 'processing',
        statusText: '处理中',
        description: '温控网关下发指令超时，需现场检查弱电信号',
        reportTime: '2026-09-02 10:45',
        engineer: '李工 (弱电班组)',
        urgency: 'high',
      },
    ],
  },
  {
    id: 'c-07',
    name: '初一(3)班',
    building: '教学楼1',
    buildingCode: 'A栋',
    roomCode: 'A-103 · 1F',
    floor: 1,
    grade: '初一',
    classNumber: '(3)班',
    status: 'normal',
    statusText: '运行正常',
    powerWatts: 880,
    todayKwh: 5.6,
    weekKwh: 36.8,
    temperature: 24.3,
    humidity: 47,
    co2Ppm: 530,
    pm25: 14,
    headTeacher: '吴丽',
    currentSubject: '生物',
    currentTeacher: '吴丽',
    courseTime: '11:05 - 11:50',
    studentCount: 45,
    presentCount: 45,
    isoPosition: { x: 50, y: 190, buildingGroup: 'b1' },
    cameras: {
      teacher: MEDIA_ASSETS.teacherCam,
      students: MEDIA_ASSETS.cam4,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '智慧黑板正常' },
      lighting: { status: 'normal', text: '照明系统正常' },
      ac: { status: 'normal', text: '空调 24°C', temp: 24, mode: '自动' },
      freshAir: { status: 'normal', text: '新风正常' },
      projector: { status: 'normal', text: '待机' },
    },
    inspectionRecords: [],
    repairOrders: [],
  },
  {
    id: 'c-08',
    name: '初二(3)班',
    building: '教学楼1',
    buildingCode: 'A栋',
    roomCode: 'A-203 · 2F',
    floor: 2,
    grade: '初二',
    classNumber: '(3)班',
    status: 'normal',
    statusText: '运行正常',
    powerWatts: 910,
    todayKwh: 5.9,
    weekKwh: 39.2,
    temperature: 24.1,
    humidity: 48,
    co2Ppm: 570,
    pm25: 15,
    headTeacher: '赵强',
    currentSubject: '政治',
    currentTeacher: '赵强',
    courseTime: '11:05 - 11:50',
    studentCount: 43,
    presentCount: 43,
    isoPosition: { x: 120, y: 190, buildingGroup: 'b1' },
    cameras: {
      teacher: MEDIA_ASSETS.teacherCam,
      students: MEDIA_ASSETS.studentCam,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '智慧黑板运行中' },
      lighting: { status: 'normal', text: '照明正常' },
      ac: { status: 'normal', text: '空调 24°C', temp: 24, mode: '制冷' },
      freshAir: { status: 'normal', text: '新风自动' },
      projector: { status: 'normal', text: '运行中' },
    },
    inspectionRecords: [],
    repairOrders: [],
  },
  {
    id: 'c-09',
    name: '初三(3)班',
    building: '教学楼1',
    buildingCode: 'A栋',
    roomCode: 'A-303 · 3F',
    floor: 3,
    grade: '初三',
    classNumber: '(3)班',
    status: 'normal',
    statusText: '运行正常',
    powerWatts: 960,
    todayKwh: 6.1,
    weekKwh: 40.5,
    temperature: 24.4,
    humidity: 46,
    co2Ppm: 590,
    pm25: 16,
    headTeacher: '钱敏',
    currentSubject: '语文',
    currentTeacher: '钱敏',
    courseTime: '11:05 - 11:50',
    studentCount: 45,
    presentCount: 44,
    isoPosition: { x: 190, y: 190, buildingGroup: 'b1' },
    cameras: {
      teacher: MEDIA_ASSETS.cam3,
      students: MEDIA_ASSETS.cam4,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '智慧黑板正常' },
      lighting: { status: 'normal', text: '照明正常' },
      ac: { status: 'normal', text: '空调 23.5°C', temp: 23.5, mode: '自动' },
      freshAir: { status: 'normal', text: '新风正常' },
      projector: { status: 'normal', text: '待机' },
    },
    inspectionRecords: [],
    repairOrders: [],
  },
  {
    id: 'c-10',
    name: '初一(4)班',
    building: '教学楼1',
    buildingCode: 'A栋',
    roomCode: 'A-104 · 1F',
    floor: 1,
    grade: '初一',
    classNumber: '(4)班',
    status: 'good',
    statusText: '节能示范 · 绿色能效',
    powerWatts: 580,
    todayKwh: 4.2,
    weekKwh: 28.5,
    temperature: 24.2,
    humidity: 46,
    co2Ppm: 500,
    pm25: 12,
    headTeacher: '韩冬梅',
    currentSubject: '美术',
    currentTeacher: '韩冬梅',
    courseTime: '11:05 - 11:50',
    studentCount: 42,
    presentCount: 42,
    isoPosition: { x: 50, y: 260, buildingGroup: 'b1' },
    cameras: {
      teacher: MEDIA_ASSETS.teacherCam,
      students: MEDIA_ASSETS.studentCam,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '智慧黑板' },
      lighting: { status: 'normal', text: '自然光感知模式' },
      ac: { status: 'normal', text: '变频节能' },
      freshAir: { status: 'normal', text: '低噪通风' },
      projector: { status: 'normal', text: '休眠' },
    },
    inspectionRecords: [],
    repairOrders: [],
  },
  {
    id: 'c-11',
    name: '初二(4)班',
    building: '教学楼1',
    buildingCode: 'A栋',
    roomCode: 'A-204 · 2F',
    floor: 2,
    grade: '初二',
    classNumber: '(4)班',
    status: 'normal',
    statusText: '运行正常',
    powerWatts: 940,
    todayKwh: 6.0,
    weekKwh: 39.8,
    temperature: 24.0,
    humidity: 47,
    co2Ppm: 560,
    pm25: 15,
    headTeacher: '冯雷',
    currentSubject: '地理',
    currentTeacher: '冯雷',
    courseTime: '11:05 - 11:50',
    studentCount: 44,
    presentCount: 44,
    isoPosition: { x: 120, y: 260, buildingGroup: 'b1' },
    cameras: {
      teacher: MEDIA_ASSETS.cam4,
      students: MEDIA_ASSETS.studentCam,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '智慧黑板运行中' },
      lighting: { status: 'normal', text: '照明正常' },
      ac: { status: 'normal', text: '空调正常' },
      freshAir: { status: 'normal', text: '新风正常' },
      projector: { status: 'normal', text: '正常' },
    },
    inspectionRecords: [],
    repairOrders: [],
  },
  {
    id: 'c-12',
    name: '初三(4)班',
    building: '教学楼1',
    buildingCode: 'A栋',
    roomCode: 'A-304 · 3F',
    floor: 3,
    grade: '初三',
    classNumber: '(4)班',
    status: 'good',
    statusText: '低耗运行',
    powerWatts: 640,
    todayKwh: 4.5,
    weekKwh: 30.2,
    temperature: 23.9,
    humidity: 45,
    co2Ppm: 510,
    pm25: 13,
    headTeacher: '沈洋',
    currentSubject: '自习',
    currentTeacher: '沈洋',
    courseTime: '11:05 - 11:50',
    studentCount: 45,
    presentCount: 45,
    isoPosition: { x: 190, y: 260, buildingGroup: 'b1' },
    cameras: {
      teacher: MEDIA_ASSETS.teacherCam,
      students: MEDIA_ASSETS.cam3,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '黑板待机' },
      lighting: { status: 'normal', text: '自习微光模式' },
      ac: { status: 'normal', text: '变频 25°C' },
      freshAir: { status: 'normal', text: '新风静音' },
      projector: { status: 'normal', text: '关' },
    },
    inspectionRecords: [],
    repairOrders: [],
  },
  {
    id: 'c-13',
    name: '初一(5)班',
    building: '教学楼1',
    buildingCode: 'A栋',
    roomCode: 'A-105 · 1F',
    floor: 1,
    grade: '初一',
    classNumber: '(5)班',
    status: 'critical',
    statusText: '设备离线告警 · 网关失联',
    powerWatts: 0,
    todayKwh: 1.2,
    weekKwh: 15.0,
    temperature: 25.5,
    humidity: 52,
    co2Ppm: 650,
    pm25: 18,
    headTeacher: '褚小明',
    currentSubject: '体育',
    currentTeacher: '褚小明 (室外)',
    courseTime: '11:05 - 11:50',
    studentCount: 45,
    presentCount: 0,
    isoPosition: { x: 50, y: 330, buildingGroup: 'b1' },
    cameras: {
      teacher: MEDIA_ASSETS.cam4,
      students: MEDIA_ASSETS.studentCam,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'offline', text: '设备通讯中断' },
      lighting: { status: 'offline', text: '回路失联' },
      ac: { status: 'offline', text: '空调离线' },
      freshAir: { status: 'offline', text: '新风离线' },
      projector: { status: 'offline', text: '离线' },
    },
    inspectionRecords: [],
    repairOrders: [
      {
        id: 'rep-5',
        ticketNo: '#rep-5',
        device: '楼层网络交换机/网关',
        status: 'pending',
        statusText: '待派工',
        description: '初一5班物联网网关无心跳回包，需检查配电箱POE交换机',
        reportTime: '2026-09-02 11:02',
        engineer: '待分配',
        urgency: 'high',
      },
    ],
  },
  {
    id: 'c-14',
    name: '初二(5)班',
    building: '教学楼1',
    buildingCode: 'A栋',
    roomCode: 'A-205 · 2F',
    floor: 2,
    grade: '初二',
    classNumber: '(5)班',
    status: 'normal',
    statusText: '运行正常',
    powerWatts: 930,
    todayKwh: 5.9,
    weekKwh: 38.5,
    temperature: 24.2,
    humidity: 47,
    co2Ppm: 540,
    pm25: 14,
    headTeacher: '卫建国',
    currentSubject: '音乐',
    currentTeacher: '卫建国',
    courseTime: '11:05 - 11:50',
    studentCount: 43,
    presentCount: 43,
    isoPosition: { x: 120, y: 330, buildingGroup: 'b1' },
    cameras: {
      teacher: MEDIA_ASSETS.teacherCam,
      students: MEDIA_ASSETS.cam3,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '多媒体音响运行' },
      lighting: { status: 'normal', text: '照明正常' },
      ac: { status: 'normal', text: '空调正常' },
      freshAir: { status: 'normal', text: '新风正常' },
      projector: { status: 'normal', text: '正常' },
    },
    inspectionRecords: [],
    repairOrders: [],
  },

  // 教学楼 2 (Group 2 - Right Block)
  {
    id: 'c-15',
    name: '高一(1)班',
    building: '教学楼2',
    buildingCode: 'B栋',
    roomCode: 'B-101 · 1F',
    floor: 1,
    grade: '高一',
    classNumber: '(1)班',
    status: 'normal',
    statusText: '运行正常',
    powerWatts: 890,
    todayKwh: 5.7,
    weekKwh: 37.2,
    temperature: 24.0,
    humidity: 46,
    co2Ppm: 550,
    pm25: 15,
    headTeacher: '蒋敏',
    currentSubject: '数学',
    currentTeacher: '蒋敏',
    courseTime: '11:05 - 11:50',
    studentCount: 48,
    presentCount: 48,
    isoPosition: { x: 350, y: 50, buildingGroup: 'b2' },
    cameras: {
      teacher: MEDIA_ASSETS.cam3,
      students: MEDIA_ASSETS.studentCam,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '智慧黑板运行中' },
      lighting: { status: 'normal', text: '标准照明' },
      ac: { status: 'normal', text: '空调 24°C' },
      freshAir: { status: 'normal', text: '新风正常' },
      projector: { status: 'normal', text: '待机' },
    },
    inspectionRecords: [],
    repairOrders: [],
  },
  {
    id: 'c-16',
    name: '高二(1)班',
    building: '教学楼2',
    buildingCode: 'B栋',
    roomCode: 'B-201 · 2F',
    floor: 2,
    grade: '高二',
    classNumber: '(1)班',
    status: 'normal',
    statusText: '运行正常',
    powerWatts: 920,
    todayKwh: 5.8,
    weekKwh: 39.0,
    temperature: 24.3,
    humidity: 47,
    co2Ppm: 570,
    pm25: 14,
    headTeacher: '沈婷',
    currentSubject: '语文',
    currentTeacher: '沈婷',
    courseTime: '11:05 - 11:50',
    studentCount: 47,
    presentCount: 47,
    isoPosition: { x: 420, y: 50, buildingGroup: 'b2' },
    cameras: {
      teacher: MEDIA_ASSETS.teacherCam,
      students: MEDIA_ASSETS.cam4,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '智慧黑板正常' },
      lighting: { status: 'normal', text: '照明正常' },
      ac: { status: 'normal', text: '空调 24°C' },
      freshAir: { status: 'normal', text: '新风正常' },
      projector: { status: 'normal', text: '正常' },
    },
    inspectionRecords: [],
    repairOrders: [],
  },
  {
    id: 'c-17',
    name: '高一(2)班',
    building: '教学楼2',
    buildingCode: 'B栋',
    roomCode: 'B-102 · 1F',
    floor: 1,
    grade: '高一',
    classNumber: '(2)班',
    status: 'critical',
    statusText: '终端离线告警 · 正在排查',
    powerWatts: 1350,
    todayKwh: 7.4,
    weekKwh: 46.2,
    temperature: 24.5,
    humidity: 48,
    co2Ppm: 620,
    pm25: 18,
    headTeacher: '李慧敏',
    currentSubject: '数学',
    currentTeacher: '陈晓明',
    courseTime: '11:05 - 11:50',
    studentCount: 46,
    presentCount: 46,
    isoPosition: { x: 350, y: 120, buildingGroup: 'b2' },
    cameras: {
      teacher: MEDIA_ASSETS.teacherCam,
      students: MEDIA_ASSETS.studentCam,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'warning', text: '触控偶尔漂移' },
      lighting: { status: 'normal', text: '照明系统 运行中' },
      ac: { status: 'warning', text: '制冷 22°C (高能耗模式)' },
      freshAir: { status: 'normal', text: '新风系统 自动' },
      projector: { status: 'normal', text: '激光投影 运行中' },
    },
    inspectionRecords: [
      {
        id: 'rec-g12',
        level: 'normal',
        levelText: '巡查正常',
        inspector: '督导组 陈主任',
        time: '2026-09-02 09:40',
        statusText: '巡查正常 / 无问题',
        content: '学生听课专注度高，课堂纪律良好，教学多媒体设备使用规范。',
        responsiblePerson: '李慧敏 (班主任)',
        deadline: '无须整改',
      },
    ],
    repairOrders: [
      {
        id: 'rep-g12',
        ticketNo: '#rep-3',
        device: '智慧黑板触控模组',
        status: 'completed',
        statusText: '维修已办结',
        description: '黑板右侧触摸有漂移，需重新校准红外触控驱动',
        reportTime: '2026-08-31 17:10',
        engineer: '张师傅 (厂家驻校工程师)',
        urgency: 'medium',
      },
    ],
  },
  {
    id: 'c-18',
    name: '高二(2)班',
    building: '教学楼2',
    buildingCode: 'B栋',
    roomCode: 'B-202 · 2F',
    floor: 2,
    grade: '高二',
    classNumber: '(2)班',
    status: 'critical',
    statusText: '高功率持续预警',
    powerWatts: 1890,
    todayKwh: 11.5,
    weekKwh: 78.0,
    temperature: 22.8,
    humidity: 50,
    co2Ppm: 680,
    pm25: 19,
    headTeacher: '朱晓东',
    currentSubject: '英语',
    currentTeacher: '朱晓东',
    courseTime: '11:05 - 11:50',
    studentCount: 48,
    presentCount: 47,
    isoPosition: { x: 420, y: 120, buildingGroup: 'b2' },
    cameras: {
      teacher: MEDIA_ASSETS.cam4,
      students: MEDIA_ASSETS.studentCam,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '智慧黑板运行中' },
      lighting: { status: 'normal', text: '全开' },
      ac: { status: 'warning', text: '双空调全力运行', temp: 21 },
      freshAir: { status: 'normal', text: '高档风' },
      projector: { status: 'normal', text: '开启' },
    },
    inspectionRecords: [],
    repairOrders: [],
  },

  // 教学楼 3 / 阶梯教室 (Group 3 - Top Middle Block)
  {
    id: 'c-19',
    name: '阶梯教室1',
    building: '教学楼3',
    buildingCode: 'C栋',
    roomCode: 'C-阶梯1 · 1F',
    floor: 1,
    grade: '公共',
    classNumber: '阶梯1',
    status: 'warning',
    statusText: '大型负荷 · 集中讲座',
    powerWatts: 2450,
    todayKwh: 16.5,
    weekKwh: 112.0,
    temperature: 23.5,
    humidity: 51,
    co2Ppm: 750,
    pm25: 20,
    headTeacher: '公共学术中心',
    currentSubject: '学术报告',
    currentTeacher: '特邀专家讲座',
    courseTime: '09:00 - 12:00',
    studentCount: 150,
    presentCount: 142,
    isoPosition: { x: 120, y: -50, buildingGroup: 'b3' },
    cameras: {
      teacher: MEDIA_ASSETS.teacherCam,
      students: MEDIA_ASSETS.cam3,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '超大屏LED矩阵' },
      lighting: { status: 'warning', text: '主席台高亮射灯' },
      ac: { status: 'warning', text: '中央空调多联机', temp: 22 },
      freshAir: { status: 'normal', text: '大功率新风强排' },
      projector: { status: 'normal', text: '双机工程投影' },
    },
    inspectionRecords: [],
    repairOrders: [],
  },
  {
    id: 'c-20',
    name: '阶梯教室2',
    building: '教学楼3',
    buildingCode: 'C栋',
    roomCode: 'C-阶梯2 · 2F',
    floor: 2,
    grade: '公共',
    classNumber: '阶梯2',
    status: 'warning',
    statusText: '大型负荷 · 学术交流',
    powerWatts: 2280,
    todayKwh: 15.2,
    weekKwh: 104.5,
    temperature: 23.8,
    humidity: 50,
    co2Ppm: 710,
    pm25: 19,
    headTeacher: '公共学术中心',
    currentSubject: '教职工大会',
    currentTeacher: '教务处',
    courseTime: '10:00 - 11:30',
    studentCount: 120,
    presentCount: 118,
    isoPosition: { x: 190, y: -50, buildingGroup: 'b3' },
    cameras: {
      teacher: MEDIA_ASSETS.cam4,
      students: MEDIA_ASSETS.studentCam,
      board: MEDIA_ASSETS.courseware,
    },
    devices: {
      blackboard: { status: 'normal', text: '大屏幕运行中' },
      lighting: { status: 'normal', text: '会议模式照明' },
      ac: { status: 'warning', text: '多联机大负荷' },
      freshAir: { status: 'normal', text: '新风大档' },
      projector: { status: 'normal', text: '工程投影' },
    },
    inspectionRecords: [],
    repairOrders: [],
  },
];

export const INITIAL_ALARMS: AlarmItem[] = [
  {
    id: 'alm-1',
    type: 'offline',
    typeText: '离线',
    level: 'critical',
    title: '高一(3)班 终端离线',
    description: '监控设备响应超时，请检查网络状态。',
    timeAgo: '10m 前',
    roomId: 'c-17',
    roomName: '高一(2)班',
    timestamp: '2026-09-02 10:55',
  },
  {
    id: 'alm-2',
    type: 'energy',
    typeText: '能耗',
    level: 'warning',
    title: '初二(2)班 功耗过高',
    description: '非教学时间段持续高功率运行。',
    timeAgo: '45m 前',
    roomId: 'c-05',
    roomName: '初二(2)班',
    timestamp: '2026-09-02 10:20',
  },
  {
    id: 'alm-3',
    type: 'device',
    typeText: '故障',
    level: 'warning',
    title: '初一(5)班 智慧网关离线',
    description: '教室PoE供电交换机通讯异常。',
    timeAgo: '1h 前',
    roomId: 'c-13',
    roomName: '初一(5)班',
    timestamp: '2026-09-02 10:05',
  },
];

export const INITIAL_PATROL_FEEDS: PatrolFeed[] = [
  {
    id: 'feed-1',
    roomId: 'c-01',
    roomName: '初一(1)班',
    teacherName: '王晓芳',
    subject: '语文',
    status: 'good',
    coverImage: MEDIA_ASSETS.teacherCam,
    isLive: true,
  },
  {
    id: 'feed-2',
    roomId: 'c-04',
    roomName: '初一(2)班',
    teacherName: '周慧敏',
    subject: '历史',
    status: 'good',
    coverImage: MEDIA_ASSETS.studentCam,
    isLive: true,
  },
  {
    id: 'feed-3',
    roomId: 'c-02',
    roomName: '初二(1)班',
    teacherName: 'Lucy Smith',
    subject: '英语',
    status: 'warning',
    coverImage: MEDIA_ASSETS.cam3,
    isLive: true,
  },
  {
    id: 'feed-4',
    roomId: 'c-05',
    roomName: '初二(2)班',
    teacherName: '李慧敏',
    subject: '数学',
    status: 'good',
    coverImage: MEDIA_ASSETS.cam4,
    isLive: true,
  },
  {
    id: 'feed-5',
    roomId: 'c-03',
    roomName: '初三(1)班',
    teacherName: '赵国庆',
    subject: '物理',
    status: 'good',
    coverImage: MEDIA_ASSETS.courseware,
    isLive: true,
  },
  {
    id: 'feed-6',
    roomId: 'c-06',
    roomName: '初三(2)班',
    teacherName: '张建国',
    subject: '化学',
    status: 'warning',
    coverImage: MEDIA_ASSETS.teacherCam,
    isLive: true,
  },
  {
    id: 'feed-7',
    roomId: 'c-15',
    roomName: '高一(1)班',
    teacherName: '陈伟强',
    subject: '地理',
    status: 'good',
    coverImage: MEDIA_ASSETS.studentCam,
    isLive: true,
  },
  {
    id: 'feed-8',
    roomId: 'c-18',
    roomName: '高二(2)班',
    teacherName: '严立华',
    subject: '生物',
    status: 'good',
    coverImage: MEDIA_ASSETS.cam3,
    isLive: true,
  },
  {
    id: 'feed-9',
    roomId: 'c-19',
    roomName: '阶梯教室1',
    teacherName: '刘德明',
    subject: '公开课',
    status: 'good',
    coverImage: MEDIA_ASSETS.cam4,
    isLive: true,
  },
];

export const HOURLY_ENERGY_DATA: EnergyHourlyPoint[] = [
  { time: '00:00', value: 30 },
  { time: '02:00', value: 32 },
  { time: '04:00', value: 28 },
  { time: '06:00', value: 25 },
  { time: '08:00', value: 65 },
  { time: '10:00', value: 78 },
  { time: '12:00', value: 72 },
  { time: '14:00', value: 92, isPeak: true },
  { time: '16:00', value: 80 },
  { time: '18:00', value: 55 },
  { time: '20:00', value: 42 },
  { time: '22:00', value: 35 },
  { time: '24:00', value: 28 },
];

export const RANKING_DATA: Record<'today' | 'week' | 'month', EnergyRankItem[]> = {
  today: [
    { rank: 1, roomId: 'c-06', roomName: '初三(2)班', valueKwh: 120, percentage: 85, trend: 'up' },
    { rank: 2, roomId: 'c-05', roomName: '初二(2)班', valueKwh: 95, percentage: 65, trend: 'up' },
    { rank: 3, roomId: 'c-18', roomName: '高二(2)班', valueKwh: 78, percentage: 50, trend: 'up' },
    { rank: 4, roomId: 'c-01', roomName: '初一(1)班', valueKwh: 52, percentage: 35, trend: 'down' },
    { rank: 5, roomId: 'c-15', roomName: '高一(1)班', valueKwh: 40, percentage: 25, trend: 'down' },
  ],
  week: [
    { rank: 1, roomId: 'c-06', roomName: '初三(2)班', valueKwh: 780, percentage: 92, trend: 'up' },
    { rank: 2, roomId: 'c-18', roomName: '高二(2)班', valueKwh: 640, percentage: 76, trend: 'up' },
    { rank: 3, roomId: 'c-05', roomName: '初二(2)班', valueKwh: 590, percentage: 68, trend: 'down' },
    { rank: 4, roomId: 'c-19', roomName: '阶梯教室1', valueKwh: 480, percentage: 54, trend: 'same' },
    { rank: 5, roomId: 'c-02', roomName: '初二(1)班', valueKwh: 340, percentage: 38, trend: 'down' },
  ],
  month: [
    { rank: 1, roomId: 'c-06', roomName: '初三(2)班', valueKwh: 3100, percentage: 95, trend: 'up' },
    { rank: 2, roomId: 'c-19', roomName: '阶梯教室1', valueKwh: 2650, percentage: 82, trend: 'up' },
    { rank: 3, roomId: 'c-18', roomName: '高二(2)班', valueKwh: 2450, percentage: 75, trend: 'same' },
    { rank: 4, roomId: 'c-05', roomName: '初二(2)班', valueKwh: 2200, percentage: 68, trend: 'down' },
    { rank: 5, roomId: 'c-17', roomName: '高一(2)班', valueKwh: 1850, percentage: 55, trend: 'down' },
  ],
};
